server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forreche/aispringcloud.git
          searchPaths: config
          username: forreche
          password: 529825.a
      label: master
eureka:
  client:
    serviceUrl:
      defaultZonr: http://localhost:8761/eureka/